coroutineDir = ./util/coroutine

link += filament \

objs += $(outtmp)/filament.o \

filament :$(coroutineDir)/Filament.cpp
	$(cppcompiler) $(obotchacppflags) -c $(coroutineDir)/Filament.cpp -o $(outtmp)/filament.o
