websocketDir = $(netDir)/websocket

objs += $(outtmp)/websocketserver.o \
		$(outtmp)/websocketserverbuilder.o \
		$(outtmp)/websocketclient.o \
		$(outtmp)/websocketprotocol.o \
		$(outtmp)/websocketframe.o \
		$(outtmp)/websocketparser.o \
		$(outtmp)/websockethybi13parser.o \
		$(outtmp)/websockethybi07parser.o \
		$(outtmp)/websockethybi08parser.o \
		$(outtmp)/websockethybi00parser.o \
		$(outtmp)/websockethybi13composer.o \
		$(outtmp)/websockethybi07composer.o \
		$(outtmp)/websockethybi08composer.o \
		$(outtmp)/websockethybi00composer.o \
		$(outtmp)/websocketpermessagedeflate.o \
		$(outtmp)/websocketlinkermanager.o \
		$(outtmp)/websocketlinker.o

$(outtmp)/websocketserver.o :$(websocketDir)/WebSocketServer.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketServer.cpp -o $(outtmp)/websocketserver.o 

$(outtmp)/websocketserverbuilder.o :$(websocketDir)/WebSocketServerBuilder.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketServerBuilder.cpp -o $(outtmp)/websocketserverbuilder.o 

$(outtmp)/websocketclient.o :$(websocketDir)/WebSocketClient.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketClient.cpp -o $(outtmp)/websocketclient.o 

$(outtmp)/websocketprotocol.o :$(websocketDir)/WebSocketProtocol.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketProtocol.cpp -o $(outtmp)/websocketprotocol.o 

$(outtmp)/websocketframe.o :$(websocketDir)/WebSocketFrame.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketFrame.cpp -o $(outtmp)/websocketframe.o 

$(outtmp)/websocketparser.o :$(websocketDir)/WebSocketParser.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketParser.cpp -o $(outtmp)/websocketparser.o 

$(outtmp)/websockethybi13parser.o :$(websocketDir)/WebSocketHybi13Parser.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi13Parser.cpp -o $(outtmp)/websockethybi13parser.o 

$(outtmp)/websockethybi07parser.o :$(websocketDir)/WebSocketHybi07Parser.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi07Parser.cpp -o $(outtmp)/websockethybi07parser.o 

$(outtmp)/websockethybi08parser.o :$(websocketDir)/WebSocketHybi08Parser.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi08Parser.cpp -o $(outtmp)/websockethybi08parser.o 

$(outtmp)/websockethybi00parser.o :$(websocketDir)/WebSocketHybi00Parser.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi00Parser.cpp -o $(outtmp)/websockethybi00parser.o 

$(outtmp)/websockethybi13composer.o :$(websocketDir)/WebSocketHybi13Composer.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi13Composer.cpp -o $(outtmp)/websockethybi13composer.o 

$(outtmp)/websockethybi07composer.o :$(websocketDir)/WebSocketHybi07Composer.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi07Composer.cpp -o $(outtmp)/websockethybi07composer.o 

$(outtmp)/websockethybi08composer.o :$(websocketDir)/WebSocketHybi08Composer.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi08Composer.cpp -o $(outtmp)/websockethybi08composer.o 

$(outtmp)/websockethybi00composer.o :$(websocketDir)/WebSocketHybi00Composer.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketHybi00Composer.cpp -o $(outtmp)/websockethybi00composer.o 

$(outtmp)/websocketpermessagedeflate.o :$(websocketDir)/WebSocketPermessageDeflate.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketPermessageDeflate.cpp -o $(outtmp)/websocketpermessagedeflate.o 

$(outtmp)/websocketlinkermanager.o :$(websocketDir)/WebSocketLinkerManager.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketLinkerManager.cpp -o $(outtmp)/websocketlinkermanager.o 

$(outtmp)/websocketlinker.o :$(websocketDir)/WebSocketLinker.cpp
	$(cppcompiler) $(obotchacppflags) -c $(websocketDir)/WebSocketLinker.cpp -o $(outtmp)/websocketlinker.o 
