sqlDir = ./sql

objs += $(outtmp)/sqlite3Client.o \

$(outtmp)/sqlite3Client.o :$(sqlDir)/sqlite3/Sqlite3Client.cpp
	$(cppcompiler) $(obotchacppflags) -c $(sqlDir)/sqlite3/Sqlite3Client.cpp -o $(outtmp)/sqlite3Client.o
